/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function clearLangCache(): void

export declare function generateTypescriptDefs(dir: string, output: string, genPlaceholder?: boolean | undefined | null): void

export declare function loadChdlang(dir: string): object

export declare function loadLang(path: string): object

export declare function loadLangs(dir: string): object
