/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function generateTypescriptDefs(dir: string, output: string, genPlaceholder?: boolean | undefined | null): void

export declare function loadCachedLangs(dir: string): object

export declare function loadLangs(dir: string): object

export declare function loadCustomLanguage(dir: string, customDir: string): object
