// THIS FILE WAS GENERATED BY SSL
// DO NOT EDIT MANUALLY OR ELSE IT WILL BE OVERWRITTEN

/* eslint-disable */

export interface Lang {
    /**
     * this is
     * a multi-line
     * string
     * test
     */
    'test': string;
    /** hello world */
    'hello': string;
}

export interface Langs {
    'e': Lang;
}

export const langs: Langs;
