// THIS FILE WAS GENERATED BY SSL
// DO NOT EDIT MANUALLY OR ELSE IT WILL BE OVERWRITTEN

/* eslint-disable */
export interface Lang {
    /**
     * [
     * "key1",
     * "key2",
     * "key3"
     * ]
     */
    'array': string[];
    /** hello world */
    'hello': string;
    /**
     * "this is
     * a multi-line
     * string
     * test"
     */
    'test': string;
}

export interface Langs {
    'e': Lang;
}

export const langs: Langs;
