pub mod cache;
pub mod loader;
pub mod parser;
use napi::{
  bindgen_prelude::{JsObjectValue, Object},
  Env, Error, Result,
};
use napi_derive::napi;
use std::fs;
use std::path::Path;

use crate::loader::{load_lang_dir, LangCache};

#[napi]
pub fn load_langs<'a>(env: &'a Env, dir: String) -> Result<Object<'a>> {
  let langs = load_lang_dir(Path::new(&dir))?;
  to_js(env, &langs)
}

#[napi]
pub fn load_cached_langs<'a>(env: &'a Env, dir: String) -> Result<Object<'a>> {
  if let Some(cached) = cache::get() {
    return to_js(env, cached);
  }

  let langs = load_lang_dir(Path::new(&dir))?;
  cache::set(langs);
  to_js(env, cache::get().unwrap())
}

fn to_js<'a>(env: &'a Env, langs: &LangCache) -> Result<Object<'a>> {
  let mut root = Object::new(env)?;
  for (lang, kv_map) in langs {
    let mut obj = Object::new(env)?;
    for (k, v) in kv_map {
      let trimmed = v.trim();
      if trimmed.starts_with('[') && trimmed.ends_with(']') {
        let inr = &trimmed[1..trimmed.len() - 1];
        let mut elm = Vec::new();
        for line in inr.lines() {
          let line = line.trim().trim_end_matches(',');
          if line.is_empty() {
            continue;
          }
          if line.starts_with('"') && line.ends_with('"') {
            elm.push(line.trim_matches('"').to_string())
          }
        }

        let mut arr = env.create_array(elm.len() as u32)?;
        for (i, val) in elm.iter().enumerate() {
          arr.set_element(i as u32, env.create_string(val)?)?
        }

        obj.set_named_property(k, arr)?;
        continue;
      }
      if trimmed.starts_with('"') && trimmed.ends_with('"') {
        let val = trimmed
          .trim_matches('"')
          .replace("\\n", "\n")
          .replace("\\\"", "\"");
        obj.set_named_property(k, env.create_string(&val)?)?;
        continue;
      }
      obj.set_named_property(k, env.create_string(v)?)?;
    }
    root.set_named_property(lang, obj)?;
  }
  Ok(root)
}
#[napi]
pub fn generate_typescript_defs(
  dir: String,
  output: String,
  gen_placeholder: Option<bool>,
) -> Result<()> {
  let langs = load_lang_dir(Path::new(&dir))?;
  let mut defs = String::new();
  defs.push_str("// THIS FILE WAS GENERATED BY SSL\n");
  defs.push_str("// DO NOT EDIT MANUALLY OR ELSE IT WILL BE OVERWRITTEN\n\n");
  defs.push_str("/* eslint-disable */\n");
  defs.push_str("export interface Lang {\n");
  let rgx = regex::Regex::new(r"\{([a-zA-Z0-9_]+)\}").unwrap();
  let should_gen_placeholder = gen_placeholder.unwrap_or(false);
  if let Some(first_lang) = langs.values().next() {
    for key in first_lang.keys() {
      if let Some(value) = first_lang.get(key) {
        let trimmed = value.trim();
        let cm: Vec<&str> = value.lines().collect();
        if cm.len() == 1 {
          defs.push_str(&format!("    /** {} */\n", cm[0]));
        } else {
          defs.push_str("    /**\n");
          for line in cm {
            defs.push_str(&format!("     * {}\n", line));
          }
          defs.push_str("     */\n");
        }
        let mut placeholders: Vec<String> = Vec::new();
        for cap in rgx.captures_iter(value) {
          if let Some(p) = cap.get(1) {
            if !placeholders.contains(&p.as_str().to_string()) {
              placeholders.push(p.as_str().to_string());
            }
          }
        }
        if !placeholders.is_empty() && should_gen_placeholder && !trimmed.starts_with('[') {
          defs.push_str(&format!("    '{}': (args: {{ ", key));
          for (i, p) in placeholders.iter().enumerate() {
            if i > 0 {
              defs.push_str(", ");
            }
            defs.push_str(&format!("{}: string", p));
          }
          defs.push_str(" }) => string;\n");
        } else if trimmed.starts_with('[') && trimmed.ends_with(']') {
          defs.push_str(&format!("    '{}': string[];\n", key));
        } else {
          defs.push_str(&format!("    '{}': string;\n", key));
        }
      }
    }
  }

  defs.push_str("}\n\n");
  defs.push_str("export interface Langs {\n");
  for lang in langs.keys() {
    defs.push_str(&format!("    '{}': Lang;\n", lang));
  }
  defs.push_str("}\n\n");
  defs.push_str("export const langs: Langs;\n");

  fs::write(output, defs)
    .map_err(|e| Error::from_reason(format!("Failed to write TypeScript definitions: {}", e)))?;
  if cfg!(debug_assertions) {
    println!("TypeScript definitions generated successfully.");
  }
  Ok(())
}
